# Generated by Django 5.2.7 on 2025-12-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_is_premium'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='مثلا 100 برای 100 درصد تخفیف', max_digits=5, null=True)),
                ('fixed_discount_amount', models.DecimalField(blank=True, decimal_places=0, help_text='مثلا 50000 برای 50 هزار تومان', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
