# Generated by Django 5.2.7 on 2025-11-30 09:59

import assessment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='sources',
            field=models.JSONField(blank=True, encoder=assessment.models.UnsafeJSONEncoder, help_text="e.g., [{'title': 'Book Name', 'link': '...'}, ...]", null=True),
        ),
    ]
