# Generated by Django 5.2.7 on 2025-11-15 20:42

import assessment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='ai_analysis',
            field=models.JSONField(blank=True, encoder=assessment.models.UnsafeJSONEncoder, null=True),
        ),
    ]
