# Generated by Django 5.2.7 on 2025-11-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_assessmentresult_ai_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='user_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='user_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='ai_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='answers',
            field=models.JSONField(default=list),
        ),
    ]
