# Generated by Django 5.2.7 on 2025-10-28 17:12

import assessment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_assessmentresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentresult',
            name='answers',
            field=models.JSONField(encoder=assessment.models.UnsafeJSONEncoder),
        ),
    ]
